feat: 提交测试

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,10 +1,33 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
+
 # 获取当前分支
 current_branch=$(git rev-parse --abbrev-ref HEAD)
 
-echo -e "\033[33m -------------------  当前分支"$current_branch" 正在对提交的代码执行操作 -------------------- \033[0m"
+# 获取目标分支
+if git rev-parse --verify MERGE_HEAD &> /dev/null; then
+  target_branch=$(git rev-parse --abbrev-ref @{u})
+else
+  target_branch="N/A"
+fi
+
+echo -e "\033[33m -------------------  当前分支: $current_branch 正在对提交的代码执行操作 -------------------- \033[0m"
+echo -e "\033[33m -------------------  目标分支: $target_branch 正在对提交的代码执行操作 -------------------- \033[0m"
+
+# 如果是尝试将其他分支合并到 test 分支，则阻止该操作
+if [ "$current_branch" != "test" ] && [ "$target_branch" = "test" ]; then
+  echo "Cannot merge from $current_branch to test branch."
+  exit 1
+fi
+
+
+
+
+# # 获取当前分支
+# current_branch=$(git rev-parse --abbrev-ref HEAD)
+
+# echo -e "\033[33m -------------------  当前分支"$current_branch" 正在对提交的代码执行操作 -------------------- \033[0m"
 
 # 检查是否有待提交的文件
 if [ -z "$(git diff --cached --name-only)" ]; then
